-- 小月亮 集中配置
-- 所有配置项通过 GetModConfigData 读取（有缓存，性能无影响）
-- 存储到全局表 _G.MOON_CFG 便于跨文件访问

local CFG = {}

CFG.ENABLE_TREASURE         = GetModConfigData("ENABLE_TREASURE")
CFG.PROXIMITY_LIMIT         = GetModConfigData("PROXIMITY_LIMIT") or 50
CFG.PLAYER_LIMIT            = GetModConfigData("PLAYER_LIMIT") or 100
CFG.GLOBAL_LIMIT            = GetModConfigData("GLOBAL_LIMIT") or 500
CFG.EXPIRY_TIME             = GetModConfigData("EXPIRY_TIME") or 480
CFG.ENABLE_QL_HELPER        = GetModConfigData("ENABLE_QL_HELPER")
CFG.LITTLE_MOON_SCALE       = GetModConfigData("LITTLE_MOON_SCALE") or 1.0
CFG.ENABLE_AUTO_PICKUP      = false -- GetModConfigData("ENABLE_AUTO_PICKUP")
CFG.DISABLE_KRAMPUS_PACK    = GetModConfigData("DISABLE_KRAMPUS_PACK")
CFG.AUTO_PICKUP_RANGE       = GetModConfigData("AUTO_PICKUP_RANGE") or 5
CFG.ENABLE_DEMON_ALTAR      = GetModConfigData("ENABLE_DEMON_ALTAR")
CFG.ENABLE_DISABLE_RESELECT = GetModConfigData("ENABLE_DISABLE_RESELECT")
CFG.ENABLE_SUICIDE          = GetModConfigData("ENABLE_SUICIDE")
-- ponytail: 上一个版本已从 modinfo 移除配置项，写死 false 防止旧档残留值生效，下个版本清理
CFG.ENABLE_LOOT_LIMITER     = false -- GetModConfigData("ENABLE_LOOT_LIMITER")
CFG.MAX_NON_STACKABLE       = GetModConfigData("MAX_NON_STACKABLE") or 5
CFG.ENABLE_SHIJIZHIHUA_BULB = GetModConfigData("ENABLE_SHIJIZHIHUA_BULB")
CFG.DIG_TREASURE_MODE       = GetModConfigData("DIG_TREASURE_MODE") or 0
CFG.MAX_NEARBY_MONSTERS     = GetModConfigData("MAX_NEARBY_MONSTERS") or 20
CFG.ENABLE_MOB_ENHANCE     = GetModConfigData("ENABLE_MOB_ENHANCE")
CFG.MOB_ENHANCE_BOSS       = GetModConfigData("MOB_ENHANCE_BOSS")
CFG.MOB_ENHANCE_NORMAL     = GetModConfigData("MOB_ENHANCE_NORMAL")
CFG.MOB_ENHANCE_LEVEL           = GetModConfigData("MOB_ENHANCE_LEVEL") or "normal"
CFG.MOB_ENCHANT_CHANCE          = GetModConfigData("MOB_ENCHANT_CHANCE") or 1.0
CFG.MOB_ENHANCE_EXCLUDE         = GetModConfigData("MOB_ENHANCE_EXCLUDE") or {}
CFG.ENABLE_MOB_DEFENSE          = GetModConfigData("ENABLE_MOB_DEFENSE")
CFG.MOB_DEFENSE_MITIGATION     = GetModConfigData("MOB_DEFENSE_MITIGATION")
CFG.MOB_DEFENSE_DYNAMIC         = GetModConfigData("MOB_DEFENSE_DYNAMIC")
CFG.MOB_DEFENSE_CAP             = GetModConfigData("MOB_DEFENSE_CAP")
CFG.MOB_DEFENSE_FREQ            = GetModConfigData("MOB_DEFENSE_FREQ")
CFG.MOB_DEFENSE_SCOPE           = GetModConfigData("MOB_DEFENSE_SCOPE") or "all"
CFG.ENABLE_MORE_ENCHANTS    = GetModConfigData("ENABLE_MORE_ENCHANTS")
CFG.remove_enchant          = GetModConfigData("remove_enchant") or {}
CFG.ENABLE_QUICK_CHAT       = GetModConfigData("ENABLE_QUICK_CHAT")
CFG.ENABLE_MOD_BROWSER      = GetModConfigData("ENABLE_MOD_BROWSER")
CFG.ENABLE_DEATH_STATS      = GetModConfigData("ENABLE_DEATH_STATS")
CFG.ENABLE_DEATH_ANNOUNCE   = GetModConfigData("ENABLE_DEATH_ANNOUNCE")
CFG.DEATH_STATS_RESET_ON_SWITCH = GetModConfigData("DEATH_STATS_RESET_ON_SWITCH")
CFG.ENABLE_WARDROBE_ANYWHERE = GetModConfigData("ENABLE_WARDROBE_ANYWHERE")
CFG.ENABLE_SKIN_SHARING     = GetModConfigData("ENABLE_SKIN_SHARING")
CFG.ENABLE_MOON_SHOP        = GetModConfigData("ENABLE_MOON_SHOP")
CFG.ENABLE_MOON_SHOP_BATCH  = GetModConfigData("ENABLE_MOON_SHOP_BATCH")
CFG.ENABLE_MOON_SHOP_BOSS_CELESTIAL = GetModConfigData("ENABLE_MOON_SHOP_BOSS_CELESTIAL")
CFG.ENABLE_MOON_SHOP_BOSS_STALKER   = GetModConfigData("ENABLE_MOON_SHOP_BOSS_STALKER")
CFG.ENABLE_MOON_SHOP_BOSS_ALTERGUARDIAN = GetModConfigData("ENABLE_MOON_SHOP_BOSS_ALTERGUARDIAN")
CFG.ENABLE_MOON_SHOP_BOSS_CRABKING       = GetModConfigData("ENABLE_MOON_SHOP_BOSS_CRABKING")
CFG.ENABLE_MOON_SHOP_BOSS_QUNYOU         = GetModConfigData("ENABLE_MOON_SHOP_BOSS_QUNYOU")
CFG.ENABLE_MOON_SHOP_SOUL   = GetModConfigData("ENABLE_MOON_SHOP_SOUL")
CFG.ENABLE_MOON_SHOP_TRAVEL_TRACES = GetModConfigData("ENABLE_MOON_SHOP_TRAVEL_TRACES")
CFG.ENABLE_MOON_SHOP_TREASURE_TALLY = GetModConfigData("ENABLE_MOON_SHOP_TREASURE_TALLY")
CFG.ENABLE_MOON_SHOP_SPARK = GetModConfigData("ENABLE_MOON_SHOP_SPARK")
CFG.ENABLE_MOON_SHOP_STAR_BROOCH = GetModConfigData("ENABLE_MOON_SHOP_STAR_BROOCH")
CFG.ENABLE_START_GIFT    = GetModConfigData("ENABLE_START_GIFT")
CFG.START_GIFT_PLANS     = GetModConfigData("START_GIFT_PLANS")
CFG.LOCK_RUN_SPEED           = GetModConfigData("LOCK_RUN_SPEED")

CFG.TRANSFORM_LIMIT         = GetModConfigData("TRANSFORM_LIMIT") or 500

GLOBAL.MOON_CFG = CFG
